"""empty message

Revision ID: 2dcb5a437a1a
Revises: 747c650a5077
Create Date: 2020-06-18 00:57:28.661248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcb5a437a1a'
down_revision = '747c650a5077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles_bkp')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bn_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gu_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ml_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mr_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('or_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pa_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('te_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ur_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('ur_title')
        batch_op.drop_column('te_title')
        batch_op.drop_column('pa_title')
        batch_op.drop_column('or_title')
        batch_op.drop_column('mr_title')
        batch_op.drop_column('ml_title')
        batch_op.drop_column('gu_title')
        batch_op.drop_column('bn_title')

    op.create_table('titles_bkp',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('en_title', sa.TEXT(), nullable=True),
    sa.Column('hi_title', sa.TEXT(), nullable=True),
    sa.Column('ministry_id', sa.INTEGER(), nullable=True),
    sa.Column('ta_title', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
