"""Adding FrozenLink

Revision ID: 326f09509cab
Revises: c7a952b5591a
Create Date: 2020-09-07 14:13:59.650817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326f09509cab'
down_revision = 'c7a952b5591a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_date'), ['date'], unique=False)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('en_title', sa.Text(), nullable=True),
    sa.Column('hi_title', sa.Text(), nullable=True),
    sa.Column('ta_title', sa.Text(), nullable=True),
    sa.Column('mr_title', sa.Text(), nullable=True),
    sa.Column('gu_title', sa.Text(), nullable=True),
    sa.Column('ur_title', sa.Text(), nullable=True),
    sa.Column('bn_title', sa.Text(), nullable=True),
    sa.Column('ml_title', sa.Text(), nullable=True),
    sa.Column('te_title', sa.Text(), nullable=True),
    sa.Column('or_title', sa.Text(), nullable=True),
    sa.Column('pa_title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frozen_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('other_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anchor_id', 'other_id', name='unique_anchor_other')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_id', sa.Integer(), nullable=True),
    sa.Column('second_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['second_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_id', 'second_id', name='unique_first_second')
    )
    op.create_table('retrieval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['retrieved_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'retrieved_id', 'model', name='unique_query_retrieved_model')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('translated', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'model', name='unique_parent_model')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    op.drop_table('retrieval')
    op.drop_table('link')
    op.drop_table('frozen_link')
    op.drop_table('titles')
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_date'))

    op.drop_table('entry')
    # ### end Alembic commands ###
