"""empty message

Revision ID: 3d3202f8699c
Revises: 
Create Date: 2020-06-16 22:25:16.367105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3202f8699c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_first_second', ['first_id', 'second_id'])

    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_parent_model', ['parent_id', 'model'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('unique_parent_model', type_='unique')
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint('unique_first_second', type_='unique')

    # ### end Alembic commands ###
