"""empty message

Revision ID: 44fcb3eacb95
Revises: 3d3202f8699c
Create Date: 2020-06-17 00:02:19.546457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fcb3eacb95'
down_revision = '3d3202f8699c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ta_title', sa.Text(), nullable=True))
        batch_op.drop_constraint('unique_title_translated', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_title_translated', ['en_title', 'nonen_title'])
        batch_op.drop_column('ta_title')

    # ### end Alembic commands ###
