"""empty message

Revision ID: 747c650a5077
Revises: 44fcb3eacb95
Create Date: 2020-06-17 01:16:10.386504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747c650a5077'
down_revision = '44fcb3eacb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_bkp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_bkp',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('en_title', sa.TEXT(), nullable=True),
    sa.Column('nonen_title', sa.TEXT(), nullable=True),
    sa.Column('ministry_id', sa.INTEGER(), nullable=True),
    sa.Column('ta_title', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
