"""empty message

Revision ID: c7a952b5591a
Revises: 2dcb5a437a1a
Create Date: 2020-06-18 01:08:00.346358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a952b5591a'
down_revision = '2dcb5a437a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bn_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gu_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ml_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mr_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('or_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pa_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('te_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ur_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('ur_title')
        batch_op.drop_column('te_title')
        batch_op.drop_column('pa_title')
        batch_op.drop_column('or_title')
        batch_op.drop_column('mr_title')
        batch_op.drop_column('ml_title')
        batch_op.drop_column('gu_title')
        batch_op.drop_column('bn_title')

    # ### end Alembic commands ###
